### ISSUE TITLE
Please add 'play_count' or preferably 'raw'

### ISSUE THREAD

**Issue by SimonvdSteen** [orsifrancesco/instagram-without-api#5]
First of all, great work you've done.

Would it be possible for you to add 'play_count' to benefit in Reels. For example you could add it like this.

Replace
```
'likes' => @ $item['like_count'],
```

With
```
'likes' => @ $item['like_count'],
'plays' => @ $item['play_count'],
```

Personally to me it would be even more beneficial to add a "raw" option, so I could output just the Raw Instagram JSON.

**Comment by orsifrancesco** [comment]
@SimonvdSteen thank you, I'm happy you appreciate it :)
Sorry for the late response.. Unfortunately this script doesn't work anymore because Instagram moved the pictures array to another endpoint (with more than one redirect) making it harder to catch images server side. Maybe I will release a new version in the future, but I don't think it can be in PHP anymore.
Right now only https://orsi.me/sniffagram/ still works, but I will add likes and plays in another moment :)
